/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowRight: typeof import('./../src/components/ArrowIcon/src/ArrowRight.vue')['default']
    BmrCalculator: typeof import('./../src/components/BmrCalculator/src/BmrCalculator.vue')['default']
    CommingSoon: typeof import('./../src/components/CommingSoon/src/CommingSoon.vue')['default']
    Content: typeof import('./../src/components/FAQDialog/src/content.md')['default']
    DialogContent: typeof import('./../src/components/FAQDialog/src/DialogContent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    FAQDialog: typeof import('./../src/components/FAQDialog/src/FAQDialog.vue')['default']
    Footer: typeof import('./../src/components/Footer/src/Footer.vue')['default']
    Header: typeof import('./../src/components/Header/src/Header.vue')['default']
    LocaleDropdown: typeof import('./../src/components/LocaleDropdown/src/LocaleDropdown.vue')['default']
    Logo: typeof import('./../src/components/Logo/src/Logo.vue')['default']
    MealPlanHeader: typeof import('./../src/components/MealPlanHeader/src/MealPlanHeader.vue')['default']
    NavDesktop: typeof import('./../src/components/Header/src/NavDesktop.vue')['default']
    NavMobile: typeof import('./../src/components/Header/src/NavMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/Sidebar/src/Sidebar.vue')['default']
    StepError: typeof import('./../src/components/StepError/src/StepError.vue')['default']
    StepsNavigator: typeof import('./../src/components/StepsNavigator/src/StepsNavigator.vue')['default']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/src/ThemeSwitch.vue')['default']
  }
}
